name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy env file
        run: cp .env.example .env

      - name: Start containers
        run: |
          docker-compose up -d
          sleep 30

      - name: Test n8n health
        run: curl --fail http://localhost:5678 || (docker-compose logs && exit 1)

      - name: Stop containers
        run: docker-compose down -v
